// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/chat/core/ports/output/aion_chat_types.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/chat/core/ports/output/aion_chat_types.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/aion_chat_types_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
