// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/record/core/ports/output/record_repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/record/core/ports/output/record_repository.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/record_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/aion-api/internal/record/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordRepository is a mock of RecordRepository interface.
type MockRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordRepositoryMockRecorder is the mock recorder for MockRecordRepository.
type MockRecordRepositoryMockRecorder struct {
	mock *MockRecordRepository
}

// NewMockRecordRepository creates a new mock instance.
func NewMockRecordRepository(ctrl *gomock.Controller) *MockRecordRepository {
	mock := &MockRecordRepository{ctrl: ctrl}
	mock.recorder = &MockRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepository) EXPECT() *MockRecordRepositoryMockRecorder {
	return m.recorder
}

// CountByTag mocks base method.
func (m *MockRecordRepository) CountByTag(ctx context.Context, tagID, userID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTag", ctx, tagID, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTag indicates an expected call of CountByTag.
func (mr *MockRecordRepositoryMockRecorder) CountByTag(ctx, tagID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTag", reflect.TypeOf((*MockRecordRepository)(nil).CountByTag), ctx, tagID, userID)
}

// CountLargeWidgetsInView mocks base method.
func (m *MockRecordRepository) CountLargeWidgetsInView(ctx context.Context, userID, viewID uint64, excludeWidgetID *uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLargeWidgetsInView", ctx, userID, viewID, excludeWidgetID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLargeWidgetsInView indicates an expected call of CountLargeWidgetsInView.
func (mr *MockRecordRepositoryMockRecorder) CountLargeWidgetsInView(ctx, userID, viewID, excludeWidgetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLargeWidgetsInView", reflect.TypeOf((*MockRecordRepository)(nil).CountLargeWidgetsInView), ctx, userID, viewID, excludeWidgetID)
}

// Create mocks base method.
func (m *MockRecordRepository) Create(ctx context.Context, r domain.Record) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecordRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecordRepository)(nil).Create), ctx, r)
}

// CreateDashboardView mocks base method.
func (m *MockRecordRepository) CreateDashboardView(ctx context.Context, view domain.DashboardView) (domain.DashboardView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDashboardView", ctx, view)
	ret0, _ := ret[0].(domain.DashboardView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDashboardView indicates an expected call of CreateDashboardView.
func (mr *MockRecordRepositoryMockRecorder) CreateDashboardView(ctx, view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDashboardView", reflect.TypeOf((*MockRecordRepository)(nil).CreateDashboardView), ctx, view)
}

// Delete mocks base method.
func (m *MockRecordRepository) Delete(ctx context.Context, id, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordRepositoryMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecordRepository)(nil).Delete), ctx, id, userID)
}

// DeleteAllByUser mocks base method.
func (m *MockRecordRepository) DeleteAllByUser(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllByUser indicates an expected call of DeleteAllByUser.
func (mr *MockRecordRepositoryMockRecorder) DeleteAllByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByUser", reflect.TypeOf((*MockRecordRepository)(nil).DeleteAllByUser), ctx, userID)
}

// DeleteDashboardView mocks base method.
func (m *MockRecordRepository) DeleteDashboardView(ctx context.Context, userID, viewID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDashboardView", ctx, userID, viewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDashboardView indicates an expected call of DeleteDashboardView.
func (mr *MockRecordRepositoryMockRecorder) DeleteDashboardView(ctx, userID, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDashboardView", reflect.TypeOf((*MockRecordRepository)(nil).DeleteDashboardView), ctx, userID, viewID)
}

// DeleteDashboardWidget mocks base method.
func (m *MockRecordRepository) DeleteDashboardWidget(ctx context.Context, userID, widgetID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDashboardWidget", ctx, userID, widgetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDashboardWidget indicates an expected call of DeleteDashboardWidget.
func (mr *MockRecordRepositoryMockRecorder) DeleteDashboardWidget(ctx, userID, widgetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDashboardWidget", reflect.TypeOf((*MockRecordRepository)(nil).DeleteDashboardWidget), ctx, userID, widgetID)
}

// DeleteGoalTemplate mocks base method.
func (m *MockRecordRepository) DeleteGoalTemplate(ctx context.Context, userID, goalTemplateID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGoalTemplate", ctx, userID, goalTemplateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGoalTemplate indicates an expected call of DeleteGoalTemplate.
func (mr *MockRecordRepositoryMockRecorder) DeleteGoalTemplate(ctx, userID, goalTemplateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGoalTemplate", reflect.TypeOf((*MockRecordRepository)(nil).DeleteGoalTemplate), ctx, userID, goalTemplateID)
}

// GetByID mocks base method.
func (m *MockRecordRepository) GetByID(ctx context.Context, recordID, userID uint64) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, recordID, userID)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRecordRepositoryMockRecorder) GetByID(ctx, recordID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRecordRepository)(nil).GetByID), ctx, recordID, userID)
}

// GetByUserCategoryDate mocks base method.
func (m *MockRecordRepository) GetByUserCategoryDate(ctx context.Context, userID, categoryID uint64, date time.Time) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCategoryDate", ctx, userID, categoryID, date)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCategoryDate indicates an expected call of GetByUserCategoryDate.
func (mr *MockRecordRepositoryMockRecorder) GetByUserCategoryDate(ctx, userID, categoryID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCategoryDate", reflect.TypeOf((*MockRecordRepository)(nil).GetByUserCategoryDate), ctx, userID, categoryID, date)
}

// GetDashboardView mocks base method.
func (m *MockRecordRepository) GetDashboardView(ctx context.Context, userID, viewID uint64) (domain.DashboardView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardView", ctx, userID, viewID)
	ret0, _ := ret[0].(domain.DashboardView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardView indicates an expected call of GetDashboardView.
func (mr *MockRecordRepositoryMockRecorder) GetDashboardView(ctx, userID, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardView", reflect.TypeOf((*MockRecordRepository)(nil).GetDashboardView), ctx, userID, viewID)
}

// ListAllBetween mocks base method.
func (m *MockRecordRepository) ListAllBetween(ctx context.Context, userID uint64, startDate, endDate time.Time, limit int) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllBetween", ctx, userID, startDate, endDate, limit)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllBetween indicates an expected call of ListAllBetween.
func (mr *MockRecordRepositoryMockRecorder) ListAllBetween(ctx, userID, startDate, endDate, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllBetween", reflect.TypeOf((*MockRecordRepository)(nil).ListAllBetween), ctx, userID, startDate, endDate, limit)
}

// ListAllUntil mocks base method.
func (m *MockRecordRepository) ListAllUntil(ctx context.Context, userID uint64, until time.Time, limit int) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUntil", ctx, userID, until, limit)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUntil indicates an expected call of ListAllUntil.
func (mr *MockRecordRepositoryMockRecorder) ListAllUntil(ctx, userID, until, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUntil", reflect.TypeOf((*MockRecordRepository)(nil).ListAllUntil), ctx, userID, until, limit)
}

// ListByCategory mocks base method.
func (m *MockRecordRepository) ListByCategory(ctx context.Context, categoryID, userID uint64, limit int, afterEventTime *string, afterID *int64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCategory", ctx, categoryID, userID, limit, afterEventTime, afterID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCategory indicates an expected call of ListByCategory.
func (mr *MockRecordRepositoryMockRecorder) ListByCategory(ctx, categoryID, userID, limit, afterEventTime, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCategory", reflect.TypeOf((*MockRecordRepository)(nil).ListByCategory), ctx, categoryID, userID, limit, afterEventTime, afterID)
}

// ListByDay mocks base method.
func (m *MockRecordRepository) ListByDay(ctx context.Context, userID uint64, date time.Time) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDay", ctx, userID, date)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDay indicates an expected call of ListByDay.
func (mr *MockRecordRepositoryMockRecorder) ListByDay(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDay", reflect.TypeOf((*MockRecordRepository)(nil).ListByDay), ctx, userID, date)
}

// ListByTag mocks base method.
func (m *MockRecordRepository) ListByTag(ctx context.Context, tagID, userID uint64, limit int, afterEventTime *string, afterID *int64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTag", ctx, tagID, userID, limit, afterEventTime, afterID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTag indicates an expected call of ListByTag.
func (mr *MockRecordRepositoryMockRecorder) ListByTag(ctx, tagID, userID, limit, afterEventTime, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTag", reflect.TypeOf((*MockRecordRepository)(nil).ListByTag), ctx, tagID, userID, limit, afterEventTime, afterID)
}

// ListByUser mocks base method.
func (m *MockRecordRepository) ListByUser(ctx context.Context, userID uint64, limit int, afterEventTime *string, afterID *int64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, afterEventTime, afterID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockRecordRepositoryMockRecorder) ListByUser(ctx, userID, limit, afterEventTime, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockRecordRepository)(nil).ListByUser), ctx, userID, limit, afterEventTime, afterID)
}

// ListDashboardViews mocks base method.
func (m *MockRecordRepository) ListDashboardViews(ctx context.Context, userID uint64) ([]domain.DashboardView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDashboardViews", ctx, userID)
	ret0, _ := ret[0].([]domain.DashboardView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDashboardViews indicates an expected call of ListDashboardViews.
func (mr *MockRecordRepositoryMockRecorder) ListDashboardViews(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDashboardViews", reflect.TypeOf((*MockRecordRepository)(nil).ListDashboardViews), ctx, userID)
}

// ListDashboardWidgetsByView mocks base method.
func (m *MockRecordRepository) ListDashboardWidgetsByView(ctx context.Context, userID, viewID uint64) ([]domain.DashboardWidget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDashboardWidgetsByView", ctx, userID, viewID)
	ret0, _ := ret[0].([]domain.DashboardWidget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDashboardWidgetsByView indicates an expected call of ListDashboardWidgetsByView.
func (mr *MockRecordRepositoryMockRecorder) ListDashboardWidgetsByView(ctx, userID, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDashboardWidgetsByView", reflect.TypeOf((*MockRecordRepository)(nil).ListDashboardWidgetsByView), ctx, userID, viewID)
}

// ListGoalTemplates mocks base method.
func (m *MockRecordRepository) ListGoalTemplates(ctx context.Context, userID uint64) ([]domain.GoalTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGoalTemplates", ctx, userID)
	ret0, _ := ret[0].([]domain.GoalTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGoalTemplates indicates an expected call of ListGoalTemplates.
func (mr *MockRecordRepositoryMockRecorder) ListGoalTemplates(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGoalTemplates", reflect.TypeOf((*MockRecordRepository)(nil).ListGoalTemplates), ctx, userID)
}

// ListLatest mocks base method.
func (m *MockRecordRepository) ListLatest(ctx context.Context, userID uint64, limit int) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLatest", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLatest indicates an expected call of ListLatest.
func (mr *MockRecordRepositoryMockRecorder) ListLatest(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLatest", reflect.TypeOf((*MockRecordRepository)(nil).ListLatest), ctx, userID, limit)
}

// ListMetricDefinitions mocks base method.
func (m *MockRecordRepository) ListMetricDefinitions(ctx context.Context, userID uint64) ([]domain.MetricDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetricDefinitions", ctx, userID)
	ret0, _ := ret[0].([]domain.MetricDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetricDefinitions indicates an expected call of ListMetricDefinitions.
func (mr *MockRecordRepositoryMockRecorder) ListMetricDefinitions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetricDefinitions", reflect.TypeOf((*MockRecordRepository)(nil).ListMetricDefinitions), ctx, userID)
}

// ReorderDashboardWidgets mocks base method.
func (m *MockRecordRepository) ReorderDashboardWidgets(ctx context.Context, userID, viewID uint64, items []domain.DashboardWidget) ([]domain.DashboardWidget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderDashboardWidgets", ctx, userID, viewID, items)
	ret0, _ := ret[0].([]domain.DashboardWidget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderDashboardWidgets indicates an expected call of ReorderDashboardWidgets.
func (mr *MockRecordRepositoryMockRecorder) ReorderDashboardWidgets(ctx, userID, viewID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderDashboardWidgets", reflect.TypeOf((*MockRecordRepository)(nil).ReorderDashboardWidgets), ctx, userID, viewID, items)
}

// SearchRecords mocks base method.
func (m *MockRecordRepository) SearchRecords(ctx context.Context, userID uint64, filters domain.SearchFilters) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRecords", ctx, userID, filters)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRecords indicates an expected call of SearchRecords.
func (mr *MockRecordRepositoryMockRecorder) SearchRecords(ctx, userID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRecords", reflect.TypeOf((*MockRecordRepository)(nil).SearchRecords), ctx, userID, filters)
}

// SetDefaultDashboardView mocks base method.
func (m *MockRecordRepository) SetDefaultDashboardView(ctx context.Context, userID, viewID uint64) (domain.DashboardView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultDashboardView", ctx, userID, viewID)
	ret0, _ := ret[0].(domain.DashboardView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDefaultDashboardView indicates an expected call of SetDefaultDashboardView.
func (mr *MockRecordRepositoryMockRecorder) SetDefaultDashboardView(ctx, userID, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultDashboardView", reflect.TypeOf((*MockRecordRepository)(nil).SetDefaultDashboardView), ctx, userID, viewID)
}

// Update mocks base method.
func (m *MockRecordRepository) Update(ctx context.Context, r domain.Record) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRecordRepositoryMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordRepository)(nil).Update), ctx, r)
}

// UpdateDashboardView mocks base method.
func (m *MockRecordRepository) UpdateDashboardView(ctx context.Context, userID, viewID uint64, name string) (domain.DashboardView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDashboardView", ctx, userID, viewID, name)
	ret0, _ := ret[0].(domain.DashboardView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDashboardView indicates an expected call of UpdateDashboardView.
func (mr *MockRecordRepositoryMockRecorder) UpdateDashboardView(ctx, userID, viewID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDashboardView", reflect.TypeOf((*MockRecordRepository)(nil).UpdateDashboardView), ctx, userID, viewID, name)
}

// UpsertDashboardWidget mocks base method.
func (m *MockRecordRepository) UpsertDashboardWidget(ctx context.Context, widget domain.DashboardWidget) (domain.DashboardWidget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDashboardWidget", ctx, widget)
	ret0, _ := ret[0].(domain.DashboardWidget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertDashboardWidget indicates an expected call of UpsertDashboardWidget.
func (mr *MockRecordRepositoryMockRecorder) UpsertDashboardWidget(ctx, widget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDashboardWidget", reflect.TypeOf((*MockRecordRepository)(nil).UpsertDashboardWidget), ctx, widget)
}

// UpsertGoalTemplate mocks base method.
func (m *MockRecordRepository) UpsertGoalTemplate(ctx context.Context, template domain.GoalTemplate) (domain.GoalTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGoalTemplate", ctx, template)
	ret0, _ := ret[0].(domain.GoalTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertGoalTemplate indicates an expected call of UpsertGoalTemplate.
func (mr *MockRecordRepositoryMockRecorder) UpsertGoalTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGoalTemplate", reflect.TypeOf((*MockRecordRepository)(nil).UpsertGoalTemplate), ctx, template)
}

// UpsertMetricDefinition mocks base method.
func (m *MockRecordRepository) UpsertMetricDefinition(ctx context.Context, definition domain.MetricDefinition) (domain.MetricDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMetricDefinition", ctx, definition)
	ret0, _ := ret[0].(domain.MetricDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertMetricDefinition indicates an expected call of UpsertMetricDefinition.
func (mr *MockRecordRepositoryMockRecorder) UpsertMetricDefinition(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMetricDefinition", reflect.TypeOf((*MockRecordRepository)(nil).UpsertMetricDefinition), ctx, definition)
}
